services:
  washere:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DB_HOST=database
      - DB_NAME=DBNAME
      - DB_USER=DBUSER
      - DB_PASS=DBPASSWORD
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=DBNAME
      - POSTGRES_USER=DBUSER
      - POSTGRES_PASSWORD=DBPASSWORD
